apiVersion: v1
kind: DaemonSet
metadata:
  name: boinc-ds
spec:
  template:
    metadata:
      name: boinc-po
      labels:
        daemon: boinc-po
    spec:
      containers:
      - name: boinc
        image: rsmitty/boinc
        env:
           - name: boincurl
             value: "www.worldcommunitygrid.org"
           - name: boinckey
             value: "1121981_b6d1a4ad2bcb77687d55c88ffa8a6374"
