apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: boinc-ds
  labels:
    k8s-app: boinc-po
spec:
  selector:
    matchLabels:
      name: boinc-po
  template:
    metadata:
      name: boinc-ds
      labels:
        name: boinc-po
        daemon: boinc-po
    spec:
      containers:
      - name: boinc
        image: rsmitty/boinc
        env:
           - name: boincurl
             value: "www.worldcommunitygrid.org"
           - name: boinckey
             value: "1121981_b6d1a4ad2bcb77687d55c88ffa8a6374"
